
server:
  port: 8083

eureka:
  instance:
    hostname: localhost  

spring:
  application:
     name: Apigateway
  cloud:
    gateway:
      routes:
      - id: DealerApi
        uri: lb://DealerApi/
        predicates:
        - Path=/dealer/**
      - id: FarmerApi
        uri: lb://FarmerApi/
        predicates:
        - Path=/farmer/**
      - id: crop-avalilable
        uri: lb://crop-avalilable/
        predicates:
        - Path=/crop/**
      - id: AdminApi
        uri: http://AdminApi/
        predicates:
        - Path=/admin/**